### ISSUE TITLE
single segment namespace

### ISSUE THREAD

**Issue by hiredman** [ericnormand/squarepeg#1]
hey

looks like squarepeg is using a single segment namespace, which means generated classes for the namespace (all functions, etc) end up in an unamed package http://java.sun.com/docs/books/jls/second_edition/html/packages.doc.html#26639

you can fix this by using a namespace with more than one segment like squarepeg.core

**Comment by ericnormand** [comment]
Hi,

Thanks for letting me know. I'll fix it.

Eric

On Wed, Aug 24, 2011 at 8:58 PM, hiredman
reply@reply.github.com
wrote:

**Comment by ericnormand** [comment]
Great. It's fixed. I moved it to squarepeg.core.

Thanks again.
